#pragma once

#include <stdint.h>

void bridge_cmd_color_bgain_direct(int p);
void bridge_cmd_color_bgain_down();
void bridge_cmd_color_bgain_reset();
void bridge_cmd_color_bgain_up();
void bridge_cmd_color_bg(int p);
void bridge_cmd_color_br(int p);
void bridge_cmd_color_chroma_suppress(uint8_t strength);
void bridge_cmd_color_gb(int p);
void bridge_cmd_color_gr(int p);
void bridge_cmd_color_level_direct(uint8_t p);
void bridge_cmd_color_level_down();
void bridge_cmd_color_level_reset();
void bridge_cmd_color_level_up();
void bridge_cmd_color_matrix_select(uint8_t p);
void bridge_cmd_color_offset_direct(int p);
void bridge_cmd_color_offset_down();
void bridge_cmd_color_offset_reset();
void bridge_cmd_color_offset_up();
void bridge_cmd_color_one_push_trigger();
void bridge_cmd_color_phase_direct(uint8_t p);
void bridge_cmd_color_phase_down();
void bridge_cmd_color_phase_reset();
void bridge_cmd_color_phase_up();
void bridge_cmd_color_rb(int p);
void bridge_cmd_color_rgain_direct(int p);
void bridge_cmd_color_rgain_down();
void bridge_cmd_color_rgain_reset();
void bridge_cmd_color_rgain_up();
void bridge_cmd_color_rg(int p);
void bridge_cmd_color_speed(uint8_t speed);
void bridge_cmd_color_white_balance_auto1();
void bridge_cmd_color_white_balance_auto2();
void bridge_cmd_color_white_balance_indoor();
void bridge_cmd_color_white_balance_manual();
void bridge_cmd_color_white_balance_one_push_wb();
void bridge_cmd_color_white_balance_outdoor();
void bridge_cmd_detail_bandwidth();
void bridge_cmd_detail_bw_balance();
void bridge_cmd_detail_crispening();
void bridge_cmd_detail_highlight_detail();
void bridge_cmd_detail_hv_balance();
void bridge_cmd_detail_level_direct(uint8_t aperture_gain);
void bridge_cmd_detail_level_down();
void bridge_cmd_detail_level_reset();
void bridge_cmd_detail_level_up();
void bridge_cmd_detail_limit();
void bridge_cmd_detail_mode();
void bridge_cmd_detail_superlow();
void bridge_cmd_exposure_ae_speed(uint8_t p);
void bridge_cmd_exposure_back_light_set(uint8_t on);
void bridge_cmd_exposure_exp_comp_direct(uint8_t p);
void bridge_cmd_exposure_exp_comp_down();
void bridge_cmd_exposure_exp_comp_reset();
void bridge_cmd_exposure_exp_comp_set(uint8_t onoff);
void bridge_cmd_exposure_exp_comp_up();
void bridge_cmd_exposure_gain_direct(int db);
void bridge_cmd_exposure_gain_down();
void bridge_cmd_exposure_gain_limit(int db);
void bridge_cmd_exposure_gain_point_position(int db);
void bridge_cmd_exposure_gain_point_set(uint8_t on);
void bridge_cmd_exposure_gain_reset();
void bridge_cmd_exposure_gain_up();
void bridge_cmd_exposure_ir_cut_filter_set(uint8_t on);
void bridge_cmd_exposure_iris_direct(uint8_t position);
void bridge_cmd_exposure_iris_down();
void bridge_cmd_exposure_iris_reset();
void bridge_cmd_exposure_iris_up();
void bridge_cmd_exposure_low_light_basis_brightness_direct(uint8_t p);
void bridge_cmd_exposure_low_light_basis_brightness_set(uint8_t on);
void bridge_cmd_exposure_minmax_shutter_set(uint8_t min, uint8_t p);
void bridge_cmd_exposure_mode_full_auto();
void bridge_cmd_exposure_mode_gain_pri();
void bridge_cmd_exposure_mode_iris_pri();
void bridge_cmd_exposure_mode_manual();
void bridge_cmd_exposure_mode_shutter_pri();
void bridge_cmd_exposure_nd_filter(uint8_t p);
void bridge_cmd_exposure_shutter_direct(uint8_t position);
void bridge_cmd_exposure_shutter_fast();
void bridge_cmd_exposure_shutter_reset();
void bridge_cmd_exposure_shutter_slow();
void bridge_cmd_exposure_spot_light_set(uint8_t on);
void bridge_cmd_exposure_vis_enh_direct(uint8_t brightn, uint8_t brightn_comp, uint8_t comp_lvl);
void bridge_cmd_exposure_vis_enh_set(uint8_t on);
void bridge_cmd_flicker_reduction_mode_set(uint8_t on);
void bridge_cmd_focus_af_sensitivity(uint8_t normal);
void bridge_cmd_focus_direct(uint32_t p);
void bridge_cmd_focus_far();
void bridge_cmd_focus_far_var(uint8_t p);
void bridge_cmd_focus_focus_inf();
void bridge_cmd_focus_ir_correction(uint8_t ir_light);
void bridge_cmd_focus_mode_auto();
void bridge_cmd_focus_mode_manual();
void bridge_cmd_focus_mode_toggle();
void bridge_cmd_focus_near();
void bridge_cmd_focus_near_limit(uint32_t p);
void bridge_cmd_focus_near_var(uint8_t p);
void bridge_cmd_focus_one_push_trigger();
void bridge_cmd_focus_stop();
void bridge_cmd_gamma_black_gamma_level(uint8_t p);
void bridge_cmd_gamma_black_gamma_range(uint8_t p);
void bridge_cmd_gamma_black_level_direct(int p);
void bridge_cmd_gamma_black_level_down();
void bridge_cmd_gamma_black_level_reset();
void bridge_cmd_gamma_black_level_up();
void bridge_cmd_gamma_level(uint8_t p);
void bridge_cmd_gamma_mode(uint8_t setting);
void bridge_cmd_gamma_offset(uint8_t polarity, uint8_t offset_width);
void bridge_cmd_gamma_pattern(uint32_t p);
void bridge_cmd_hdmi_color_space(uint8_t rgb);
void bridge_cmd_hdmi_video_format_change(int w, int h, int f, char l);
void bridge_cmd_knee_mode(uint8_t manual);
void bridge_cmd_knee_point(uint8_t p);
void bridge_cmd_knee_set(uint8_t on);
void bridge_cmd_knee_slope(uint8_t p);
void bridge_cmd_menu_display_off();
void bridge_cmd_noise_reduction_2d_3d_manual_setting(uint8_t lvl_2d, uint8_t lvl_3d);
void bridge_cmd_noise_reduction_mode_level_set(uint8_t p);
void bridge_cmd_pan_tilt_absolute_move(uint8_t speed, uint8_t p[5], uint8_t t[4]);
void bridge_cmd_pan_tilt_directionals(int vert, int horiz, uint8_t pan_speed, uint8_t tilt_speed);
void bridge_cmd_pan_tilt_home();
void bridge_cmd_pan_tilt_limit_clear(uint8_t position);
void bridge_cmd_pan_tilt_limit_set(uint8_t position, uint8_t p[5], uint8_t t[4]);
void bridge_cmd_pan_tilt_ramp_curve(int p);
void bridge_cmd_pan_tilt_relative_move(uint8_t speed, uint8_t p[5], uint8_t t[4]);
void bridge_cmd_pan_tilt_reset();
void bridge_cmd_pan_tilt_slow_mode(int p);
void bridge_cmd_picture_profile_mode(uint8_t p);
void bridge_cmd_preset_drive_speed(uint8_t pn_speed, uint8_t direction_speed);
void bridge_cmd_preset_mode(uint8_t p);
void bridge_cmd_preset_recall();
void bridge_cmd_preset_reset();
void bridge_cmd_preset_set();
void bridge_cmd_ptz_trace_delete(uint8_t trace_num);
void bridge_cmd_ptz_trace_play(uint8_t start, uint8_t trace_num);
void bridge_cmd_ptz_trace_rec(uint8_t start, uint8_t trace_num);
void bridge_cmd_system_hphase_direct(uint32_t p);
void bridge_cmd_system_hphase_set(uint8_t on);
void bridge_cmd_system_img_flip(uint8_t on);
void bridge_cmd_system_pan_reverse(uint8_t on);
void bridge_cmd_system_tilt_reverse(uint8_t on);
void bridge_cmd_tarry_set(uint8_t on);
void bridge_cmd_tarry_tally_mode(uint8_t mode);
void bridge_cmd_zoom_clear_image_set(uint8_t on);
void bridge_cmd_zoom_direct(uint32_t p);
void bridge_cmd_zoom_stop();
void bridge_cmd_zoom_tele();
void bridge_cmd_zoom_teleconvert_mode(uint8_t on);
void bridge_cmd_zoom_tele_var(uint8_t p);
void bridge_cmd_zoom_wide();
void bridge_cmd_zoom_wide_var(uint8_t p);

void bridge_cmd_memory_reset(uint8_t num);
void bridge_cmd_memory_set(uint8_t num);
void bridge_cmd_memory_recall(uint8_t num);
void bridge_cmd_pan_tilt_relative_position(int pan_speed, int tilt_speed, int pan_pos, int tilt_pos);
void bridge_cmd_pan_tilt_absolute_position(int pan_speed, int tilt_speed, int pan_pos, int tilt_pos);

